# Lectura de JSON

```Python
url="https://api.github.com/users/hadley/orgs"
```

[Página de formateo de JSON](https://jsonformatter.curiousconcept.com/)

#### Lectura con pandas

In [1]:
import pandas as pd
url="https://raw.githubusercontent.com/json-iterator/test-data/master/large-file.json"
pd.read_json(url).head()

,id,type,actor,repo,payload,public,created_at,org
0,2489651045,CreateEvent,"{'id': 665991, 'login': 'petroav', 'gravatar_i...","{'id': 28688495, 'name': 'petroav/6.828', 'url...","{'ref': 'master', 'ref_type': 'branch', 'maste...",True,2015-01-01 15:00:00+00:00,NaN
1,2489651051,PushEvent,"{'id': 3854017, 'login': 'rspt', 'gravatar_id'...","{'id': 28671719, 'name': 'rspt/rspt-theme', 'u...","{'push_id': 536863970, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:01+00:00,NaN
2,2489651053,PushEvent,"{'id': 6339799, 'login': 'izuzero', 'gravatar_...","{'id': 28270952, 'name': 'izuzero/xe-module-aj...","{'push_id': 536863972, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:01+00:00,NaN
3,2489651057,WatchEvent,"{'id': 6894991, 'login': 'SametSisartenep', 'g...","{'id': 2871998, 'name': 'visionmedia/debug', '...",{'action': 'started'},True,2015-01-01 15:00:03+00:00,"{'id': 9285252, 'login': 'visionmedia', 'grava..."
4,2489651062,PushEvent,"{'id': 485033, 'login': 'winterbe', 'gravatar_...","{'id': 28593843, 'name': 'winterbe/streamjs', ...","{'push_id': 536863975, 'size': 1, 'distinct_si...",True,2015-01-01 15:00:03+00:00,NaN

#### Lectura local

In [2]:
import json
with open('main.json') as f:
    data = json.load(f)

#### Lectura con requests

In [3]:
import json
import requests

response = requests.get(url)
todos = json.loads(response.text)

In [4]:
todos

[{'id': '2489651045',
  'type': 'CreateEvent',
  'actor': {'id': 665991,
   'login': 'petroav',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/petroav',
   'avatar_url': 'https://avatars.githubusercontent.com/u/665991?'},
  'repo': {'id': 28688495,
   'name': 'petroav/6.828',
   'url': 'https://api.github.com/repos/petroav/6.828'},
  'payload': {'ref': 'master',
   'ref_type': 'branch',
   'master_branch': 'master',
   'description': "Solution to homework and assignments from MIT's 6.828 (Operating Systems Engineering). Done in my spare time.",
   'pusher_type': 'user'},
  'public': True,
  'created_at': '2015-01-01T15:00:00Z'},
 {'id': '2489651051',
  'type': 'PushEvent',
  'actor': {'id': 3854017,
   'login': 'rspt',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/rspt',
   'avatar_url': 'https://avatars.githubusercontent.com/u/3854017?'},
  'repo': {'id': 28671719,
   'name': 'rspt/rspt-theme',
   'url': 'https://api.github.com/repos/rspt/rspt-theme'},
  'payload': {'push_id': 536863970,
   'size': 1,
   'distinct_size': 1,
   'ref': 'refs/heads/master',
   'head': '6b089eb4a43f728f0a594388092f480f2ecacfcd',
   'before': '437c03652caa0bc4a7554b18d5c0a394c2f3d326',
   'commits': [{'sha': '6b089eb4a43f728f0a594388092f480f2ecacfcd',
     'author': {'email': '5c682c2d1ec4073e277f9ba9f4bdf07e5794dabe@rspt.ch',
      'name': 'rspt'},
     'message': 'Fix main header height on mobile',
     'distinct': True,
     'url': 'https://api.github.com/repos/rspt/rspt-theme/commits/6b089eb4a43f728f0a594388092f480f2ecacfcd'}]},
  'public': True,
  'created_at': '2015-01-01T15:00:01Z'},
 {'id': '2489651053',
  'type': 'PushEvent',
  'actor': {'id': 6339799,
   'login': 'izuzero',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/izuzero',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6339799?'},
  'repo': {'id': 28270952,
   'name': 'izuzero/xe-module-ajaxboard',
   'url': 'https://api.github.com/repos/izuzero/xe-module-ajaxboard'},
  'payload': {'push_id': 536863972,
   'size': 1,
   'distinct_size': 1,
   'ref': 'refs/heads/develop',
   'head': 'ec819b9df4fe612bb35bf562f96810bf991f9975',
   'before': '590433109f221a96cf19ea7a7d9a43ca333e3b3e',
   'commits': [{'sha': 'ec819b9df4fe612bb35bf562f96810bf991f9975',
     'author': {'email': 'df05f55543db3c62cf64f7438018ec37f3605d3c@gmail.com',
      'name': 'Eunsoo Lee'},
     'message': '#20 게시글 및 댓글 삭제 시 새로고침이 되는 문제 해결\n\n원래 의도는 새로고침이 되지 않고 확인창만으로 해결되어야 함.\n기본 게시판 대응 플러그인에서 발생한 이슈.',
     'distinct': True,
     'url': 'https://api.github.com/repos/izuzero/xe-module-ajaxboard/commits/ec819b9df4fe612bb35bf562f96810bf991f9975'}]},
  'public': True,
  'created_at': '2015-01-01T15:00:01Z'},
 {'id': '2489651057',
  'type': 'WatchEvent',
  'actor': {'id': 6894991,
   'login': 'SametSisartenep',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/SametSisartenep',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6894991?'},
  'repo': {'id': 2871998,
   'name': 'visionmedia/debug',
   'url': 'https://api.github.com/repos/visionmedia/debug'},
  'payload': {'action': 'started'},
  'public': True,
  'created_at': '2015-01-01T15:00:03Z',
  'org': {'id': 9285252,
   'login': 'visionmedia',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/visionmedia',
   'avatar_url': 'https://avatars.githubusercontent.com/u/9285252?'}},
 {'id': '2489651062',
  'type': 'PushEvent',
  'actor': {'id': 485033,
   'login': 'winterbe',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/winterbe',
   'avatar_url': 'https://avatars.githubusercontent.com/u/485033?'},
  'repo': {'id': 28593843,
   'name': 'winterbe/streamjs',
   'url': 'https://api.github.com/repos/winterbe/streamjs'},
  'payload': {'push_id': 536863975,
   'size': 1,
   'distinct_size': 1,
   'ref': 'refs/heads/master',
   'head': '15b303203be31bd295bc831075da8f74b99b3981',
   'before': '0fef99f604154ccfe1d2fcd0aadeffb5c58e43ff',
   'commits': [{'sha': '15b303203be31bd295bc831075da8f74b99b3981',
     'author': {'email': '52a47bffd52d9cea1ee1362f2bd0c5f87fac9262@googlemail.com',
      'name': 'Benjamin Winterberg'},
     'message': 'Add comparator support for min, max operations',
     'distinct': True,
     'url': 'https://api.github.com/repos/winterbe/streamjs/commits/15b303203be31bd295bc831075da8f74b99b3981'}]},
  'public': True,
  'created_at': '2015-01-01T15:00:03Z'},
 {'id': '2489651063',
  'type': 'PushEvent',
  'actor': {'id': 4319954,
   'login': 'hermanwahyudi',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hermanwahyudi',
   'avatar_url': 'https://avatars.githubusercontent.com/u/4319954?'},
  'repo': {'id': 27826205,
   'name': 'hermanwahyudi/selenium',
   'url': 'https://api.github.com/repos/hermanwahyudi/selenium'},
  'payload': {'push_id': 536863976,
   'size': 1,
   'distinct_size': 0,
   'ref': 'refs/heads/master',
   'head': '1b58dd4c4e14ea9cf5212b981774bd448a266c3c',
   'before': '20b10e3a605bd177efff62f1130943774ac07bf3',
   'commits': [{'sha': '1b58dd4c4e14ea9cf5212b981774bd448a266c3c',
     'author': {'email': '2bb20d8a71fb7adbc1d6239cc9ff4130f26819dc@gmail.com',
      'name': 'Herman'},
     'message': 'Update README.md',
     'distinct': False,
     'url': 'https://api.github.com/repos/hermanwahyudi/selenium/commits/1b58dd4c4e14ea9cf5212b981774bd448a266c3c'}]},
  'public': True,
  'created_at': '2015-01-01T15:00:03Z'},
 {'id': '2489651064',
  'type': 'PushEvent',
  'actor': {'id': 2881602,
   'login': 'jdilt',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jdilt',
   'avatar_url': 'https://avatars.githubusercontent.com/u/2881602?'},
  'repo': {'id': 28682546,
   'name': 'jdilt/jdilt.github.io',
   'url': 'https://api.github.com/repos/jdilt/jdilt.github.io'},
  'payload': {'push_id': 536863977,
   'size': 1,
   'distinct_size': 1,
   'ref': 'refs/heads/master',
   'head': 'd13cbd1e5c68b189fc91cfa14fdae1f52ef6f9e1',
   'before': '8515c4a9efb40332659e4389821a73800ce6a4bf',
   'commits': [{'sha': 'd13cbd1e5c68b189fc91cfa14fdae1f52ef6f9e1',
     'author': {'email': '3e9bbe622d800410f1d4d0a4bb92004e147f1b1e@163.com',
      'name': 'jdilt'},
     'message': 'refine index page and about page',
     'distinct': True,
     'url': 'https://api.github.com/repos/jdilt/jdilt.github.io/commits/d13cbd1e5c68b189fc91cfa14fdae1f52ef6f9e1'}]},
  'public': True,
  'created_at': '2015-01-01T15:00:03Z'},
 {'id': '2489651066',
  'type': 'PushEvent',
  'actor': {'id': 3495129,
   'login': 'sundaymtn',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/sundaymtn',
   'avatar_url': 'https://avatars.githubusercontent.com/u/3495129?'},
  'repo': {'id': 24147122,
   'name': 'sundaymtn/waterline',
   'url': 'https://api.github.com/repos/sundaymtn/waterline'},
  'payload': {'push_id': 536863979,
   'size': 1,
   'distinct_size': 1,
   'ref': 'refs/heads/master',
   'head': '2a2ec35bfefb9341b1df2f213aad1dac804bc2ea',
   'before': 'a7dba8faf22d2f342b7398ff76bfd10a30106191',
   'commits': [{'sha': '2a2ec35bfefb9341b1df2f213aad1dac804bc2ea',
     'author': {'email': '7fbc091194a9488bfb16868527a7c3a8ba469dba@gmail.com',
      'name': 'Seth Carter'},
     'message': 'Thu Jan  1 10:00:02 EST 2015',
     'distinct': True,
     'url': 'https://api.github.com/repos/sundaymtn/waterline/commits/2a2ec35bfefb9341b1df2f213aad1dac804bc2ea'}]},
  'public': True,
  'created_at': '2015-01-01T15:00:04Z'},
 {'id': '2489651067',
  'type': 'PushEvent',
  'actor': {'id': 10363514,
   'login': 'zhouzhi2015',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/zhouzhi2015',
   'avatar_url': 'https://avatars.githubusercontent.com/u/10363514?'},
  'repo': {'id': 28686619,
   'name': 'zhouzhi2015/temp',
   'url': 'https://api.github.com/repos/zhouzhi2015/temp'},
  'payload': {'push_id': 536863980,
   'size': 1,
   'distinct_size': 1,
   'ref': 'refs/heads/master',
   'head': '22019c081480435bb7d6e629766f2204c6c219bd',
   'before': 'd5926ef8c6a8a43724f8dc94007c3c5a918391c3',
   'commits': [{'sha': '22019c081480435bb7d6e629766f2204c6c219bd',
     'author': {'email': '421c4f4cb8c7fe07ea1166286558dc42a56cf3a7',
      'name': '1184795629@qq.com'},
     'message': '测测',
     'distinct': True,
     'url': 'https://api.github.com/repos/zhouzhi2015/temp/commits/22019c081480435bb7d6e629766f2204c6c219bd'}]},
  'public': True,
  'created_at': '2015-01-01T15:00:04Z'},
 {'id': '2489651071',
  'type': 'ReleaseEvent',
  'actor': {'id': 7659931,
   'login': 'petrkutalek',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/petrkutalek',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7659931?'},
  'repo': {'id': 20029610,
   'name': 'petrkutalek/png2pos',
   'url': 'https://api.github.com/repos/petrkutalek/png2pos'},
  'payload': {'action': 'published',
   'release': {'url': 'https://api.github.com/repos/petrkutalek/png2pos/releases/818676',
    'assets_url': 'https://api.github.com/repos/petrkutalek/png2pos/releases/818676/assets',
    'upload_url': 'https://uploads.github.com/repos/petrkutalek/png2pos/releases/818676/assets{?name}',
    'html_url': 'https://github.com/petrkutalek/png2pos/releases/tag/v1.5.4',
    'id': 818676,
    'tag_name': 'v1.5.4',
    'target_commitish': 'master',
    'name': '',
    'draft': False,
    'author': {'login': 'petrkutalek',
     'id': 7659931,
     'avatar_url': 'https://avatars.githubusercontent.com/u/7659931?v=3',
     'gravatar_id': '',
     'url': 'https://api.github.com/users/petrkutalek',
     'html_url': 'https://github.com/petrkutalek',
     'followers_url': 'https://api.github.com/users/petrkutalek/followers',
     'following_url': 'https://api.github.com/users/petrkutalek/following{/other_user}',
     'gists_url': 'https://api.github.com/users/petrkutalek/gists{/gist_id}',
     'starred_url': 'https://api.github.com/users/petrkutalek/starred{/owner}{/repo}',
     'subscriptions_url': 'https://api.github.com/users/petrkutalek/subscriptions',
     'organizations_url': 'https://api.github.com/users/petrkutalek/orgs',
     'repos_url': 'https://api.github.com/users/petrkutalek/repos',
     'events_url': 'https://api.github.com/users/petrkutalek/events{/privacy}',
     'received_events_url': 'https://api.github.com/users/petrkutalek/received_events',
     'type': 'User',
     'site_admin': False},
    'prerelease': False,
    'created_at': '2015-01-01T14:56:44Z',
    'published_at': '2015-01-01T15:00:05Z',
    'assets': [{'url': 'https://api.github.com/repos/petrkutalek/png2pos/releases/assets/362298',
      'id': 362298,
      'name': 'png2pos-v1.5.4-linux.zip',
      'label': None,
      'uploader': {'login': 'petrkutalek',
       'id': 7659931,
       'avatar_url': 'https://avatars.githubusercontent.com/u/7659931?v=3',
       'gravatar_id': '',
       'url': 'https://api.github.com/users/petrkutalek',
       'html_url': 'https://github.com/petrkutalek',
       'followers_url': 'https://api.github.com/users/petrkutalek/followers',
       'following_url': 'https://api.github.com/users/petrkutalek/following{/other_user}',
       'gists_url': 'https://api.github.com/users/petrkutalek/gists{/gist_id}',
       'starred_url': 'https://api.github.com/users/petrkutalek/starred{/owner}{/repo}',
       'subscriptions_url': 'https://api.github.com/users/petrkutalek/subscriptions',
       'organizations_url': 'https://api.github.com/users/petrkutalek/orgs',
       'repos_url': 'https://api.github.com/users/petrkutalek/repos',
       'events_url': 'https://api.github.com/users/petrkutalek/events{/privacy}',
       'received_events_url': 'https://api.github.com/users/petrkutalek/received_events',
       'type': 'User',
       'site_admin': False},
      'content_type': 'application/zip',
      'state': 'uploaded',
      'size': 37781,
      'download_count': 0,
      'created_at': '2015-01-01T14:59:22Z',
      'updated_at': '2015-01-01T14:59:23Z',
      'browser_download_url': 'https://github.com/petrkutalek/png2pos/releases/download/v1.5.4/png2pos-v1.5.4-linux.zip'},
     {'url': 'https://api.github.com/repos/petrkutalek/png2pos/releases/assets/362297',
      'id': 362297,
      'name': 'png2pos-v1.5.4-linux.zip.asc',
      'label': None,
      'uploader': {'login': 'petrkutalek',
       'id': 7659931,
       'avatar_url': 'https://avatars.githubusercontent.com/u/7659931?v=3',
       'gravatar_id': '',
       'url': 'https://api.github.com/users/petrkutalek',
       'html_url': 'https://github.com/petrkutalek',
       'followers_url': 'https://api.github.com/users/petrkutalek/followers',
       'following_url': 'https://api.github.com/users/petrkutalek/following{/other_user}',
       'gists_url': 'https://api.github.com/users/petrkutalek/gists{/gist_id}',
       'starred_url': 'https://api.github.com/users/petrkutalek/starred{/owner}{/repo}',
       'subscriptions_url': 'https://api.github.com/users/petrkutalek/subscriptions',
       'organizations_url': 'https://api.github.com/users/petrkutalek/orgs',
       'repos_url': 'https://api.github.com/users/petrkutalek/repos',
       'events_url': 'https://api.github.com/users/petrkutalek/events{/privacy}',
       'received_events_url': 'https://api.github.com/users/petrkutalek/received_events',
       'type': 'User',
       'site_admin': False},
      'content_type': 'text/plain',
      'state': 'uploaded',
      'size': 495,
      'download_count': 0,
      'created_at': '2015-01-01T14:59:21Z',
      'updated_at': '2015-01-01T14:59:22Z',
      'browser_download_url': 'https://github.com/petrkutalek/png2pos/releases/download/v1.5.4/png2pos-v1.5.4-linux.zip.asc'},
     {'url': 'https://api.github.com/repos/petrkutalek/png2pos/releases/assets/362299',
      'id': 362299,
      'name': 'png2pos-v1.5.4-osx.zip',
      'label': None,
      'uploader': {'login': 'petrkutalek',
       'id': 7659931,
       'avatar_url': 'https://avatars.githubusercontent.com/u/7659931?v=3',
       'gravatar_id': '',
       'url': 'https://api.github.com/users/petrkutalek',
       'html_url': 'https://github.com/petrkutalek',
       'followers_url': 'https://api.github.com/users/petrkutalek/followers',
       'following_url': 'https://api.github.com/users/petrkutalek/following{/other_user}',
       'gists_url': 'https://api.github.com/users/petrkutalek/gists{/gist_id}',
       'starred_url': 'https://api.github.com/users/petrkutalek/starred{/owner}{/repo}',
       'subscriptions_url': 'https://api.github.com/users/petrkutalek/subscriptions',
       'organizations_url': 'https://api.github.com/users/petrkutalek/orgs',
       'repos_url': 'https://api.github.com/users/petrkutalek/repos',
       'events_url': 'https://api.github.com/users/petrkutalek/events{/privacy}',
       'received_events_url': 'https://api.github.com/users/petrkutalek/received_events',
       'type': 'User',
       'site_admin': False},
      'content_type': 'application/zip',
      'state': 'uploaded',
      'size': 27891,
      'download_count': 0,
      'created_at': '2015-01-01T14:59:30Z',
      'updated_at': '2015-01-01T14:59:32Z',
      'browser_download_url': 'https://github.com/petrkutalek/png2pos/releases/download/v1.5.4/png2pos-v1.5.4-osx.zip'},
     {'url': 'https://api.github.com/repos/petrkutalek/png2pos/releases/assets/362300',
      'id': 362300,
      'name': 'png2pos-v1.5.4-osx.zip.asc',
      'label': None,
      'uploader': {'login': 'petrkutalek',
       'id': 7659931,
       'avatar_url': 'https://avatars.githubusercontent.com/u/7659931?v=3',
       'gravatar_id': '',
       'url': 'https://api.github.com/users/petrkutalek',
       'html_url': 'https://github.com/petrkutalek',
       'followers_url': 'https://api.github.com/users/petrkutalek/followers',
       'following_url': 'https://api.github.com/users/petrkutalek/following{/other_user}',
       'gists_url': 'https://api.github.com/users/petrkutalek/gists{/gist_id}',
       'starred_url': 'https://api.github.com/users/petrkutalek/starred{/owner}{/repo}',
       'subscriptions_url': 'https://api.github.com/users/petrkutalek/subscriptions',
       'organizations_url': 'https://api.github.com/users/petrkutalek/orgs',
       'repos_url': 'https://api.github.com/users/petrkutalek/repos',
       'events_url': 'https://api.github.com/users/petrkutalek/events{/privacy}',
       'received_events_url': 'https://api.github.com/users/petrkutalek/received_events',
       'type': 'User',
       'site_admin': False},
      'content_type': 'text/plain',
      'state': 'uploaded',
      'size': 495,
      'download_count': 0,
      'created_at': '2015-01-01T14:59:30Z',
      'updated_at': '2015-01-01T14:59:33Z',
      'browser_download_url': 'https://github.com/petrkutalek/png2pos/releases/download/v1.5.4/png2pos-v1.5.4-osx.zip.asc'}],
    'tarball_url': 'https://api.github.com/repos/petrkutalek/png2pos/tarball/v1.5.4',
    'zipball_url': 'https://api.github.com/repos/petrkutalek/png2pos/zipball/v1.5.4',
    'body': ''}},
  'public': True,
  'created_at': '2015-01-01T15:00:05Z'},
 {'id': '2489651077',
  'type': 'PushEvent',
  'actor': {'id': 4070158,
   'login': 'caleb-eades',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/caleb-eades',
   'avatar_url': 'https://avatars.githubusercontent.com/u/4070158?'},
  'repo': {'id': 20469468,
   'name': 'caleb-eades/MinecraftServers',
   'url': 'https://api.github.com/repos/caleb-eades/MinecraftServers'},
  'payload': {'push_id': 536863983,
   'size': 1,
   'distinct_size': 1,
   'ref': 'refs/heads/master',
   'head': '6ea9a1f5b0b3c4204272a5fe2587a5ee146c3a49',
   'before': '8e94c95939b8f7db4c085da258698f07ae2b9cf3',
   'commits': [{'sha': '6ea9a1f5b0b3c4204272a5fe2587a5ee146c3a49',
     'author': {'email': '5bbfe2c07a3ef0b22b72711a2edf1c023f6433c5@gmail.com',
      'name': 'caleb-eades'},
     'message': 'Auto Snapshot Server State',
     'distinct': True,
     'url': 'https://api.github.com/repos/caleb-eades/MinecraftServers/commits/6ea9a1f5b0b3c4204272a5fe2587a5ee146c3a49'}]},
  'public': True,
  'created_at': '2015-01-01T15:00:05Z'},
 {'id': '2489651078',
  'type': 'WatchEvent',
  'actor': {'id': 285289,
   'login': 'comcxx11',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/comcxx11',
   'avatar_url': 'https://avatars.githubusercontent.com/u/285289?'},
  'repo': {'id': 5569958,
   'name': 'phpsysinfo/phpsysinfo',
   'url': 'https://api.github.com/repos/phpsysinfo/phpsysinfo'},
  'payload': {'action': 'started'},
  'public': True,
  'created_at': '2015-01-01T15:00:05Z',
  'org': {'id': 6797923,
   'login': 'phpsysinfo',
   'gravatar_id': '',
   'url': 'https://api.github.com/orgs/phpsysinfo',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6797923?'}},
 {'id': '2489651080',
  'type': 'WatchEvent',
  'actor': {'id': 1757814,
   'login': 'Soufien',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Soufien',
   'avatar_url': 'https://avatars.githubusercontent.com/u/1757814?'},
  'repo': {'id': 25873041,
   'name': 'wasabeef/awesome-android-libraries',
   'url': 'https://api.github.com/repos/wasabeef/awesome-android-libraries'},
  'payload': {'action': 'started'},
  'public': True,
  'created_at': '2015-01-01T15:00:05Z'},
 {'id': '2489651083',
  'type': 'PushEvent',
  'actor': {'id': 9538449,
   'login': 'hcremers',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hcremers',
   'avatar_url': 'https://avatars.githubusercontent.com/u/9538449?'},
  'repo': {'id': 26101634,
   'name': 'ktgw0316/LightZone-l10n-nl',
   'url': 'https://api.github.com/repos/ktgw0316/LightZone-l10n-nl'},
  'payload': {'push_id': 536863987,
   'size': 1,
   'distinct_size': 1,
   'ref': 'refs/heads/master',
   'head': '0fca01b12e6a8a1c537842d4831906d1eb4a277e',
   'before': 'fe610605ba48a87ee7c9bcf1a8a8db5f51bc4b58',
   'commits': [{'sha': '0fca01b12e6a8a1c537842d4831906d1eb4a277e',
     'author': {'email': '8800578b51f022c8d8adb9606a8b3db4fedbdac6@192.168.0.167',
      'name': 'hans'},
     'message': 'Translated by hcremers',
     'distinct': True,

Vemos qué tipo de datos es esto

In [5]:
print(type(todos))
len(todos)

<class 'list'>

11351

Es un iterable, por lo que podremos recorrerlo mediante un for, y de esta manera ver qué hay dentro

In [6]:
for i in todos:
    print(i.keys())

dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at', 'org'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])
dict_keys(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at'])

#### Obtención de datos

Primero vamos a probar a sacar todos los url.

In [9]:
datos = {'url': []}

for i in todos:
    
    repo = i.get('repo', None)
    if repo is not None:
        nombre_url = repo.get('url', 'NO URL')
    
    datos['url'].append(nombre_url)

    
datos

{'url': ['https://api.github.com/repos/petroav/6.828',
  'https://api.github.com/repos/rspt/rspt-theme',
  'https://api.github.com/repos/izuzero/xe-module-ajaxboard',
  'https://api.github.com/repos/visionmedia/debug',
  'https://api.github.com/repos/winterbe/streamjs',
  'https://api.github.com/repos/hermanwahyudi/selenium',
  'https://api.github.com/repos/jdilt/jdilt.github.io',
  'https://api.github.com/repos/sundaymtn/waterline',
  'https://api.github.com/repos/zhouzhi2015/temp',
  'https://api.github.com/repos/petrkutalek/png2pos',
  'https://api.github.com/repos/caleb-eades/MinecraftServers',
  'https://api.github.com/repos/phpsysinfo/phpsysinfo',
  'https://api.github.com/repos/wasabeef/awesome-android-libraries',
  'https://api.github.com/repos/ktgw0316/LightZone-l10n-nl',
  'https://api.github.com/repos/leethomason/tinyxml2',
  'https://api.github.com/repos/edx/edx-platform',
  'https://api.github.com/repos/yhoonkim/GraphBoard',
  'https://api.github.com/repos/dartist/raytracer',
  'https://api.github.com/repos/SundeepK/Clone',
  'https://api.github.com/repos/mevlan/script',
  'https://api.github.com/repos/suneg/dojo_rules',
  'https://api.github.com/repos/blang/btrfs-initrd',
  'https://api.github.com/repos/vatsaaa/mycodesnips',
  'https://api.github.com/repos/suneg/dojo_rules',
  'https://api.github.com/repos/GeneAssembly/biosal',
  'https://api.github.com/repos/greatfire/wiki',
  'https://api.github.com/repos/adamatan/flip_classroom_hackathon',
  'https://api.github.com/repos/googlesamples/android-testing',
  'https://api.github.com/repos/walmik/timer.jquery',
  'https://api.github.com/repos/Laxamer/Txtr',
  'https://api.github.com/repos/greatfire/z',
  'https://api.github.com/repos/PhantomWolf/Whitelist-PAC-generator',
  'https://api.github.com/repos/basheersubei/ofSamplesAndStuff',
  'https://api.github.com/repos/SeleniumHQ/irc-logs',
  'https://api.github.com/repos/sheimi/SGit',
  'https://api.github.com/repos/xtuaok/twitter_track_following',
  'https://api.github.com/repos/wasabeef/awesome-android-libraries',
  'https://api.github.com/repos/RusticiSoftware/TinCanJS',
  'https://api.github.com/repos/missionsix/Transmissionbt',
  'https://api.github.com/repos/designingsean/tce-wordpress-theme',
  'https://api.github.com/repos/xenim/livestatus-publicpage',
  'https://api.github.com/repos/wechat-distribution/distribution',
  'https://api.github.com/repos/nmap/nmap',
  'https://api.github.com/repos/su-github-machine-user/github-nagios-check',
  'https://api.github.com/repos/RusticiSoftware/TinCanJS',
  'https://api.github.com/repos/luigino/Baka-MPlayer',
  'https://api.github.com/repos/wyldckat/wyldckat.github.io',
  'https://api.github.com/repos/treckstar/yolo-octo-hipster',
  'https://api.github.com/repos/tamil1/tamil1.github.io',
  'https://api.github.com/repos/nilegsalcin/puppet-bootstrap',
  'https://api.github.com/repos/chrisduan/mychat',
  'https://api.github.com/repos/evilmartians/postcss',
  'https://api.github.com/repos/HouseMonitor/Logs2014-2015',
  'https://api.github.com/repos/Blimeo/blimeo.github.io',
  'https://api.github.com/repos/d3stats/d3.fuzz.me.uk',
  'https://api.github.com/repos/OQO/websocket-sharp',
  'https://api.github.com/repos/machchk/report',
  'https://api.github.com/repos/Khan/khan-i18n',
  'https://api.github.com/repos/jkchapman/LibGDX-GameOfLife',
  'https://api.github.com/repos/trustedsec/social-engineer-toolkit',
  'https://api.github.com/repos/cptnnick/F3_PA',
  'https://api.github.com/repos/sjahl/user-env',
  'https://api.github.com/repos/konjac/calendars',
  'https://api.github.com/repos/maybezi/project',
  'https://api.github.com/repos/WordPoints/wordpointsorg',
  'https://api.github.com/repos/quixing/help-me',
  'https://api.github.com/repos/kless/dat',
  'https://api.github.com/repos/izuzero/xe-module-ajaxboard',
  'https://api.github.com/repos/n1k0/casperjs',
  'https://api.github.com/repos/NixOS/nixpkgs',
  'https://api.github.com/repos/weakish/greylist',
  'https://api.github.com/repos/Abeer-y/Ultimatum-Game-on-A-Barabasi-Albert-Network',
  'https://api.github.com/repos/mozilla/Fira',
  'https://api.github.com/repos/izuzero/xe-module-ajaxboard',
  'https://api.github.com/repos/deeperx/dojo_rules',
  'https://api.github.com/repos/cptnnick/F3_PA',
  'https://api.github.com/repos/InternetDevels/drupalcores',
  'https://api.github.com/repos/hex7c0/grunt-endline',
  'https://api.github.com/repos/chris-roerig/52-projects',
  'https://api.github.com/repos/USunOfBeach/GrimDawnZH',
  'https://api.github.com/repos/prakhar1989/awesome-courses',
  'https://api.github.com/repos/hamini/sqlalchem',
  'https://api.github.com/repos/okomok/vim-scala',
  'https://api.github.com/repos/xoyip/Brewfile',
  'https://api.github.com/repos/crdroidandroid/android_packages_apps_Settings',
  'https://api.github.com/repos/yiyizym/blog',
  'https://api.github.com/repos/vascon8/appium-dot-app',
  'https://api.github.com/repos/blang/btrfs-initrd',
  'https://api.github.com/repos/KenanSulayman/heartbeat',
  'https://api.github.com/repos/silverpower/comrade_erika',
  'https://api.github.com/repos/Saisi/secret-octo-wookie',
  'https://api.github.com/repos/hkairi/agendakar-widget',
  'https://api.github.com/repos/prakhar1989/awesome-courses',
  'https://api.github.com/repos/tj/commander.js',
  'https://api.github.com/repos/jpespinal/portfolio',
  'https://api.github.com/repos/brunocarvalhodearaujo/datastore',
  'https://api.github.com/repos/LiuSmile/StuGit',
  'https://api.github.com/repos/kevinzhow/Waver',
  'https://api.github.com/repos/SBPrime/AsyncWorldEdit',
  'https://api.github.com/repos/USunOfBeach/GrimDawnZH',
  'https://api.github.com/repos/bigsquirrel/bigsquirrel.github.io',
  'https://api.github.com/repos/frank-deng/fgfs-tools',
  'https://api.github.com/repos/USunOfBeach/GrimDawnZH',
  'https://api.github.com/repos/wix/react-templates',
  'https://api.github.com/repos/torvalds/linux',
  'https://api.github.com/repos/Adidaz/callingCard',
  'https://api.github.com/repos/callumW/map_generator',
  'https://api.github.com/repos/markbirbeck/sublime-text-shell-command',
  'https://api.github.com/repos/yunqy/ShareDictionary',
  'https://api.github.com/repos/OQO/websocket-sharp',
  'https://api.github.com/repos/akiokanashiki/tdwf',
  'https://api.github.com/repos/floscher/linguist',
  'https://api.github.com/repos/GaryCarneiro/dotfiles',
  'https://api.github.com/repos/OQO/websocket-sharp',
  'https://api.github.com/repos/pyqt/python-qt5',
  'https://api.github.com/repos/pedant/safe-java-js-webview-bridge',
  'https://api.github.com/repos/vanakenm/fullstack-challenges',
  'https://api.github.com/repos/DevPress/DP-Dashboard',
  'https://api.github.com/repos/Adaptivity/AlchemyPlusPlus',
  'https://api.github.com/repos/micahyoung/citibike-data',
  'https://api.github.com/repos/kamranahmedse/kamranahmedse.github.io',
  'https://api.github.com/repos/BimbaLaszlo/vim-eight',
  'https://api.github.com/repos/micahyoung/cbstats-data',
  'https://api.github.com/repos/CRXTeam/android_frameworks_base',
  'https://api.github.com/repos/quhezheng/HomeIP',
  'https://api.github.com/repos/MinecraftForge/MinecraftForge',
  'https://api.github.com/repos/0x73/Oc',
  'https://api.github.com/repos/akeeba/akeebasubs',
  'https://api.github.com/repos/lollipoop/android_vendor_omni',
  'https://api.github.com/repos/avishayil/wordpress-post-fb-url-linter',
  'https://api.github.com/repos/SrJosue1/Testing',
  'https://api.github.com/repos/kaltura/platform-install-packages',
  'https://api.github.com/repos/Ratmir15/hz-base',
  'https://api.github.com/repos/iOS-7-Lessons/Matched-Up',
  'https://api.github.com/repos/hex7c0/json-decrypt',
  'https://api.github.com/repos/stevensouza/testproject',
  'https://api.github.com/repos/piotrzalewski/GAEPrime',
  'https://api.github.com/repos/willfarrell/alfred-youtube-workflow',
  'https://api.github.com/repos/syon/andy-hiroyuki.github.io',
  'https://api.github.com/repos/osler/World-of-Warcraft-Modding',
  'https://api.github.com/repos/crdroidandroid/android_packages_apps_Settings',
  'https://api.github.com/repos/brunocarvalhodearaujo/datastore',
  'https://api.github.com/repos/Derathir/PCaPP',
  'https://api.github.com/repos/namangoel1/gci',
  'https://api.github.com/repos/BSI-Business-Systems-Integration-AG/org.eclipsescout.demo',
  'https://api.github.com/repos/edx/edx-platform',
  'https://api.github.com/repos/t9md/vim-choosewin',
  'https://api.github.com/repos/crdroidandroid/android_packages_apps_Settings',
  'https://api.github.com/repos/markbirbeck/sublime-text-shell-command',
  'https://api.github.com/repos/craiglockwood/lardylockwoods',
  'https://api.github.com/repos/jingyuan4ever/checkio',
  'https://api.github.com/repos/kaltura/server',
  'https://api.github.com/repos/bitpay/bitcore',
  'https://api.github.com/repos/bitpay/bitcore',
  'https://api.github.com/repos/eclecticlogic/pedal-loader',
  'https://api.github.com/repos/samdark/yiifeed',
  'https://api.github.com/repos/spf13/hugo',
  'https://api.github.com/repos/mquinson/PLM-data',
  'https://api.github.com/repos/dezelin/Timetable',
  'https://api.github.com/repos/StartEnd/codeDemo',
  'https://api.github.com/repos/gocardless/activejob-retry',
  'https://api.github.com/repos/osrf/www.ros.org',
  'https://api.github.com/repos/fpc-svn/lazarus',
  'https://api.github.com/repos/wrldwzrd89/mazer-5d',
  'https://api.github.com/repos/mevlan/script',
  'https://api.github.com/repos/atheme/charybdis',
  'https://api.github.com/repos/daviddenton/memebot',
  'https://api.github.com/repos/CatTail/cattail.github.io',
  'https://api.github.com/repos/Realcraft/Realcraft',
  'https://api.github.com/repos/matplotlib/matplotlib',
  'https://api.github.com/repos/hanjos/nexus',
  'https://api.github.com/repos/Randati/cjdrs',
  'https://api.github.com/repos/EricSchles/typecheck',
  'https://api.github.com/repos/kaltura/platform-install-packages',
  'https://api.github.com/repos/brunocarvalhodearaujo/datastore',
  'https://api.github.com/repos/lognormal/boomerang',
  'https://api.github.com/repos/ClemensAhrens/coref',
  'https://api.github.com/repos/evanx/vellum',
  'https://api.github.com/repos/jakimfett/AlchemyPlusPlus',
  'https://api.github.com/repos/RoryCrispin/chive',
  'https://api.github.com/repos/misoobu/gree-community',
  'https://api.github.com/repos/superlucky84/superlucky',
  'https://api.github.com/repos/ElsaBonnaud/WebSite',
  'https://api.github.com/repos/kiminozo/BgmOnWp',
  'https://api.github.com/repos/toddmotto/echo',
  'https://api.github.com/repos/Oderik/xbmc-somafm',
  'https://api.github.com/repos/Oderik/xbmc-somafm',
  'https://api.github.com/repos/Learningroots/www_src',
  'https://api.github.com/repos/qianlifeng/Wox.Plugin.Everything',
  'https://api.github.com/repos/brunocarvalhodearaujo/datastore',
  'https://api.github.com/repos/qkalantary/Antswer',
  'https://api.github.com/repos/gocardless/activejob-retry',
  'https://api.github.com/repos/opscode/omnibus-chef',
  'https://api.github.com/repos/Realcraft/Realcraft',
  'https://api.github.com/repos/ratpack/ratpack',
  'https://api.github.com/repos/osler/World-of-Warcraft-Modding',
  'https://api.github.com/repos/fossasia/fossasia15',
  'https://api.github.com/repos/Woseseltops/signbank',
  'https://api.github.com/repos/apascual89/packages_apps_Settings',
  'https://api.github.com/repos/vinta/awesome-python',
  'https://api.github.com/repos/stig/.emacs.d',
  'https://api.github.com/repos/shlomizadok/foreman_openscap',
  'https://api.github.com/repos/cjolowicz/scripts',
  'https://api.github.com/repos/LucasZheng/LucasZheng.github.io',
  'https://api.github.com/repos/lyftclothing/lyftclothing.github.io',
  'https://api.github.com/repos/Raulfin/PCaPP',
  'https://api.github.com/repos/Xexanos/PoorOres',
  'https://api.github.com/repos/Xexanos/PoorOres',
  'https://api.github.com/repos/KenanSulayman/heartbeat',
  'https://api.github.com/repos/reclaimhosting/federated-wiki',
  'https://api.github.com/repos/chancecoin/chancecoinj',
  'https://api.github.com/repos/epambench/tdd',
  'https://api.github.com/repos/magicwheel/agent-core-and-example',
  'https://api.github.com/repos/chrisduan/mychat',
  'https://api.github.com/repos/eranif/codelite',
  'https://api.github.com/repos/koalalorenzo/python-digitalocean',
  'https://api.github.com/repos/FiLeVeR10/zenity-ui',
  'https://api.github.com/repos/cdpython/blog',
  'https://api.github.com/repos/Fisab/fisab',
  'https://api.github.com/repos/manuth/Untitled-Project',
  'https://api.github.com/repos/Jamesking56/Cachet',
  'https://api.github.com/repos/Blimeo/blimeo.github.io',
  'https://api.github.com/repos/stubbornella/type-o-matic',
  'https://api.github.com/repos/google/material-design-icons',
  'https://api.github.com/repos/AxelRL/AxelRL.github.io',
  'https://api.github.com/repos/itadakimas/maths-matrices',
  'https://api.github.com/repos/brunocarvalhodearaujo/datastore',
  'https://api.github.com/repos/michey/templates-LUFA',
  'https://api.github.com/repos/TooTallNate/Java-WebSocket',
  'https://api.github.com/repos/onlyutkarsh/OpenConfigurationManager',
  'https://api.github.com/repos/MeirKriheli/Open-Knesset',
  'https://api.github.com/repos/Fumes007/Material',
  'https://api.github.com/repos/thessrb/thessrbio',
  'https://api.github.com/repos/mdt207/GDo-kon',
  'https://api.github.com/repos/meltingice/psd.js',
  'https://api.github.com/repos/cdpython/cdpython.github.io',
  'https://api.github.com/repos/ratpack/ratpack',
  'https://api.github.com/repos/chrisduan/mychat',
  'https://api.github.com/repos/chrisduan/mychat',
  'https://api.github.com/repos/Woseseltops/signbank',
  'https://api.github.com/repos/shahzad-latif/testrepo',
  'https://api.github.com/repos/jadar/DeveloperCapes',
  'https://api.github.com/repos/SeleniumHQ/docs',
  'https://api.github.com/repos/sundaymtn/waterline',
  'https://api.github.com/repos/marcuswestin/WebViewJavascriptBridge',
  'https://api.github.com/repos/fermino/WhatsBot',
  'https://api.github.com/repos/mevlan/script',
  'https://api.github.com/repos/quixing/help-me',
  'https://api.github.com/repos/qdm/qdm.github.io',
  'https://api.github.com/repos/poliander/skeleton-sdcc-cpc',
  'https://api.github.com/repos/astefanutti/camel-cdi',
  'https://api.github.com/repos/g0v/moedict-app',
  'https://api.github.com/repos/freeweibo/top',
  'https://api.github.com/repos/suprafly/knodes',
  'https://api.github.com/repos/lihechao/pl0Compiler',
  'https://api.github.com/repos/peti/nixpkgs',
  'https://api.github.com/repos/jeffbyrnes/alfred-pkgman-workflow',
  'https://api.github.com/repos/taukir4u/ResultUIApp',
  'https://api.github.com/repos/vatsaaa/mycodesnips',
  'https://api.github.com/repos/yiisoft/yii2-bootstrap',
  'https://api.github.com/repos/jzoldak/edx-platform',
  'https://api.github.com/repos/siigna/web',
  'https://api.github.com/repos/Daverball/mkxp',
  'https://api.github.com/repos/giorgia-amici/testing_angular_exmples',
  'https://api.github.com/repos/bardsoftware/ace',
  'https://api.github.com/repos/tommy351/Octopress-Theme-Slash',
  'https://api.github.com/repos/drjorgepolanco/depot',
  'https://api.github.com/repos/dorleosterode/gt-scaffold',
  'https://api.github.com/repos/prateekagr98/Fork-Read-Node',
  'https://api.github.com/repos/Automattic/socket.io',
  'https://api.github.com/repos/ev3dev/ev3dev.github.io',
  'https://api.github.com/repos/Coders-Tree/tree-collab',
  'https://api.github.com/repos/filip-daca/shimmer',
  'https://api.github.com/repos/slluis/cydin',
  'https://api.github.com/repos/Poornaprajna-Technologies/test',
  'https://api.github.com/repos/zordius/gulp-github',
  'https://api.github.com/repos/abhardwaj/datahub',
  'https://api.github.com/repos/lvyunyi/tutorial-ror',
  'https://api.github.com/repos/manmyung/study-4clojure',
  'https://api.github.com/repos/yasaricli/metrello',
  'https://api.github.com/repos/rebar/rebar3',
  'https://api.github.com/repos/emersion/bups',
  'https://api.github.com/repos/xcatliu/xcat',
  'https://api.github.com/repos/Sjeiti/TinySort',
  'https://api.github.com/repos/aliaksandr-pasynkau/express-verifier',
  'https://api.github.com/repos/aliaksandr-pasynkau/express-verifier',
  'https://api.github.com/repos/zachsnow/ng-inline',
  'https://api.github.com/repos/MovingBlocks/Terasology',
  'https://api.github.com/repos/JoaoPedroPinheiro/laig1415',
  'https://api.github.com/repos/vatsaaa/mycodesnips',
  'https://api.github.com/repos/xujiaao/AARLinkSources',
  'https://api.github.com/repos/gorhill/uBlock',
  'https://api.github.com/repos/silverpower/comrade_erika',
  'https://api.github.com/repos/wheresmybento/runningman',
  'https://api.github.com/repos/exuperok/dojo_rules',
  'https://api.github.com/repos/Trial-In-Error/changes',
  'https://api.github.com/repos/HakurouKen/douban.fm-api',
  'https://api.github.com/repos/somaopensource/docker',
  'https://api.github.com/repos/blakgeek/flurry-phonegap-plugin',
  'https://api.github.com/repos/sickill/vim-monokai',
  'https://api.github.com/repos/atelierspierrot/assets-manager',
  'https://api.github.com/repos/brunocarvalhodearaujo/datastore',
  'https://api.github.com/repos/gurunars/gurunars.github.io',
  'https://api.github.com/repos/d3rp/ansible-modules-core',
  'https://api.github.com/repos/vincenthz/hs-scraps',
  'https://api.github.com/repos/wkcool/wkcool.github.com',
  'https://api.github.com/repos/bborbe/prototype',
  'https://api.github.com/repos/khcr/coursesApp-doc',
  'https://api.github.com/repos/Tonvin/oh-my-zsh',
  'https://api.github.com/repos/MattisLind/PC04Reader',
  'https://api.github.com/repos/buptjz/Pixel',
  'https://api.github.com/repos/lihechao/pl0Compiler',
  'https://api.github.com/repos/weshellnet/weshellnet.github.io',
  'https://api.github.com/repos/swegener/gentoo-portage',
  'https://api.github.com/repos/jokeewu/jokeewu.github.io',
  'https://api.github.com/repos/mevlan/script',
  'https://api.github.com/repos/Irkka/botfarmd',
  'https://api.github.com/repos/KenanSulayman/heartbeat',
  'https://api.github.com/repos/mevlan/script',
  'https://api.github.com/repos/jquery/jquery-mobile',
  'https://api.github.com/repos/scut/fea-geotechnical-solver',
  'https://api.github.com/repos/hasadna/Open-Knesset',
  'https://api.github.com/repos/kchmck/vim-coffee-script',
  'https://api.github.com/repos/vatsaaa/mycodesnips',
  'https://api.github.com/repos/alfredessa/pythonda2015',
  'https://api.github.com/repos/Payum/PayumBundle',
  'https://api.github.com/repos/abhinav-garg/web-page',
  'https://api.github.com/repos/Payum/PayumBundle',
  'https://api.github.com/repos/callumW/map_generator',
  'https://api.github.com/repos/imgix/imgix-emacs',
  'https://api.github.com/repos/formapro-forks/PayumBundle',
  'https://api.github.com/repos/LnxPrgr3/crossfeed',
  'https://api.github.com/repos/DalekVoid/Compass-And-Straightedge-Construction',
  'https://api.github.com/repos/lucasayat/jardinor',
  'https://api.github.com/repos/deeperx/dojo_rules',
  'https://api.github.com/repos/Antinomy/Tech-Doc',
  'https://api.github.com/repos/alexz202/dedetozp',
  'https://api.github.com/repos/expressjs/errorhandler',
  'https://api.github.com/repos/AxelRL/AxelRL.github.io',
  'https://api.github.com/repos/ddollar/heroku-buildpack-multi',
  'https://api.github.com/repos/cdpython/blog',
  'https://api.github.com/repos/nouon/weiyi',
  'https://api.github.com/repos/google/fruit',
  'https://api.github.com/repos/inf0rmer/blanket',
  'https://api.github.com/repos/addyosmani/a11y',
  'https://api.github.com/repos/SlowlyTeam/BulletinBoard',
  'https://api.github.com/repos/sunilrebel/spann-jira',
  'https://api.github.com/repos/drrb/java-rust-example',
  'https://api.github.com/repos/raspberry-node/node-rpi-ws281x-native',
  'https://api.github.com/repos/adamkennedy/PPI',
  'https://api.github.com/repos/patrick-hudson/EggDrop',
  'https://api.github.com/repos/gnenbu/gn_enbu_chs',
  'https://api.github.com/repos/shimbara/jersey_rest_ws',
  'https://api.github.com/repos/jquast/x84',

Ahora obtendremos más info.

In [11]:
datos = {'name': [],
        'url': [],
        'id': []
        }

for i in todos:
    repo = i.get('repo', None)
    if repo is not None:
        nombre_url = repo.get('url', 'NO URL')
        nombre_name = repo.get('name', 'NO NAME')
        nombre_id = repo.get('id', 'NO ID')
    
        datos['url'].append(nombre_url)
        datos['name'].append(nombre_name)
        datos['id'].append(nombre_id)
    
pd.DataFrame(datos).head()

,name,url,id
0,petroav/6.828,https://api.github.com/repos/petroav/6.828,28688495
1,rspt/rspt-theme,https://api.github.com/repos/rspt/rspt-theme,28671719
2,izuzero/xe-module-ajaxboard,https://api.github.com/repos/izuzero/xe-module...,28270952
3,visionmedia/debug,https://api.github.com/repos/visionmedia/debug,2871998
4,winterbe/streamjs,https://api.github.com/repos/winterbe/streamjs,28593843