# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd 
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
url="https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo=pd.read_csv(url, sep="\t")

In [4]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

# Name of the max valued product

In [6]:
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

In [10]:
chipo.loc[chipo["item_name"].idxmax()]

order_id                                                            304
quantity                                                              1
item_name                                             Veggie Soft Tacos
choice_description    [Tomatillo Red Chili Salsa, [Fajita Vegetables...
item_price                                                        11.25
Name: 738, dtype: object

3598    Chips and Fresh Tomato Salsa
Name: item_name, dtype: object

                         item_name
3598  Chips and Fresh Tomato Salsa

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

In [13]:
(chipo["item_price"] > 10.00).value_counts

<bound method IndexOpsMixin.value_counts of 0       False
1       False
2       False
3       False
4        True
        ...
4617     True
4618     True
4619     True
4620    False
4621    False
Name: item_price, Length: 4622, dtype: bool>

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [26]:
chipo["unit_price"]=chipo["item_price"]/chipo["quantity"]

chipo.groupby("item_name")["unit_price"]

chipo[["item_name", "unit_price"]]

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [28]:
chipo.sort_values(by='item_name', ascending=False)

,order_id,quantity,item_name,choice_description,item_price,unit_price
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98,8.49
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
...,...,...,...,...,...,...
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49,6.49
3789,1517,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1392,566,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
3614,1448,1,6 Pack Soft Drink,[Nestea],6.49,6.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

In [31]:
chipo.sort_values(by='unit_price', ascending=False).head(1)

,order_id,quantity,item_name,choice_description,item_price,unit_price
3749,1499,1,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89,11.89

V2

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [34]:
(chipo["item_name"]=="Veggie Salad Bowl").sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [36]:
((chipo["item_name"]=="Canned Soda") & (chipo["quantity"] > 1)).sum()

np.int64(20)